name: MobDisguise
main: me.desmin88.mobdisguise.MobDisguise
version: 1.1
authors: [desmin88]
depend: [BukkitContrib]
commands:
    md:
        description: Allows player to disguise as mob
        usage: /md [disguise,undisguise,types]
permissions:
    mobdisguise.use:
        description: Allows a player to disguise as a mob
    