name: MobDisguise
main: me.desmin88.mobdisguise.MobDisguise
version: 1.7
authors: [desmin88]
commands:
    md:
        description: Allows player to disguise as mob
        usage: /md [mobtype], stats
permissions:
    mobdisguise.*:
        description: Allows a player to disguise as any mob
        children:
            mobdisguise.creeper: true
            mobdisguise.skeleton: true
            mobdisguise.spider: true
            mobdisguise.giant: true
            mobdisguise.zombie: true
            mobdisguise.slime: true
            mobdisguise.ghast: true
            mobdisguise.pigman: true
            mobdisguise.pig: true
            mobdisguise.sheep: true
            mobdisguise.cow: true
            mobdisguise.chicken: true
            mobdisguise.squid: true
            mobdisguise.wolf: true
            mobdisguise.steve: true
            mobdisguise.player: true
            mobdisguise.enderman: true
            mobdisguise.cavespider: true
            mobdisguise.silverfish: true
            mobdisguise.villager: true
            mobdisguise.snowgolem: true
            mobdisguise.mooshroom: true
            mobdisguise.blaze: true
            mobdisguise.magmacube: true
            mobdisguise.enderdragon: true
            mobdisguise.baby: true
    mobdisguise.creeper:
        description: Allows a player to disguise as a creeper
    mobdisguise.skeleton:
        description: Allows a player to disguise as a skeleton
    mobdisguise.spider:
        description: Allows a player to disguise as a spider
    mobdisguise.giant:
        description: Allows a player to disguise as a giant
    mobdisguise.zombie:
        description: Allows a player to disguise as a zombie
    mobdisguise.slime:
        description: Allows a player to disguise as a slime
    mobdisguise.ghast:
        description: Allows a player to disguise as a ghast
    mobdisguise.pigman:
        description: Allows a player to disguise as a pigman        
    mobdisguise.pig:
        description: Allows a player to disguise as a pig
    mobdisguise.sheep:
        description: Allows a player to disguise as a sheep
    mobdisguise.cow:
        description: Allows a player to disguise as a cow
    mobdisguise.chicken:
        description: Allows a player to disguise as a chicken
    mobdisguise.squid:
        description: Allows a player to disguise as a squid
    mobdisguise.wolf:
        description: Allows a player to disguise as a wolf
    mobdisguise.steve:
        description: Allows a player to disguise as Steve
    mobdisguise.player:
        description: Allows a player to disguise as any player
    mobdisguise.enderman:
        description: Allows a player to disguise as an enderman
    mobdisguise.cavespider:
        description: Allows a player to disguise as a cavespider
    mobdisguise.silverfish:
        description: Allows a player to disguise as a silverfish
    mobdisguise.villager: 
        description: Allows a player to disguise as villager
    mobdisguise.snowgolem: 
        description: Allows a player to disguise as a snow golem
    mobdisguise.mooshroom: 
        description: Allows a player to disguise as a mooshroom
    mobdisguise.blaze: 
        description: Allows a player to disguise as a blaze
    mobdisguise.magmacube: 
        description: Allows a player to disguise as a magmacube
    mobdisguise.enderdragon: 
        description: Allows a player to disguise as an enderdragon
    mobdisguise.baby:
        description: Allows player to become a baby animal